/*
 * Copyright 2026 KoreDB Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pankaj.koredb.engine

import com.pankaj.koredb.db.KoreDatabase
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.Serializable
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import java.io.File
import java.util.UUID

class ErgonomicFeaturesTest {

    private lateinit var testDir: File

    @Serializable
    data class Product(val id: String, val title: String, val category: String, val price: Double)

    @Serializable
    data class LogMessage(val text: String, val level: String)

    @Before
    fun setUp() {
        testDir = File("build/tmp/test_ergonomic_${UUID.randomUUID()}")
        testDir.mkdirs()
    }

    @After
    fun tearDown() {
        testDir.deleteRecursively()
    }

    // ========================================================================
    // 1. BATCH DELETE & DELETE ALL
    // ========================================================================

    @Test
    fun testDeleteBatchAndCleanSecondaryIndexes() = runBlocking {
        val db = KoreDatabase(testDir)
        val products = db.collection<Product>("products")
        products.createIndex("category") { it.category }
        products.createNumericIndex("price") { it.price }

        for (i in 1..10) {
            products.insert("p$i", Product("p$i", "Product $i", "Electronics", i * 100.0))
        }

        assertEquals(10, products.count())
        assertEquals(10, products.query().whereEq("category", "Electronics").execute().size)

        // Delete batch of 4 items
        products.deleteBatch(listOf("p1", "p3", "p5", "p7"))

        assertEquals(6, products.count())
        assertNull(products.getById("p1"))
        assertNull(products.getById("p3"))
        assertNotNull(products.getById("p2"))

        // Secondary index should immediately reflect deletions
        val matching = products.query().whereEq("category", "Electronics").execute()
        assertEquals(6, matching.size)
        assertFalse(matching.any { it.id == "p1" || it.id == "p3" })

        // Clear remaining documents with deleteAll()
        products.deleteAll()
        assertEquals(0, products.count())
        assertTrue(products.getAll().isEmpty())

        db.close()
    }

    // ========================================================================
    // 2. DROP COLLECTION
    // ========================================================================

    @Test
    fun testDropCollection() = runBlocking {
        val db = KoreDatabase(testDir)
        val sessionCache = db.collection<Product>("session_cache")

        sessionCache.insert("s1", Product("s1", "Session 1", "Auth", 0.0))
        sessionCache.insert("s2", Product("s2", "Session 2", "Auth", 0.0))
        assertEquals(2, sessionCache.count())

        db.dropCollection("session_cache")

        // Opening collection fresh should show it is completely empty
        val freshCol = db.collection<Product>("session_cache")
        assertEquals(0, freshCol.count())
        assertNull(freshCol.getById("s1"))

        db.close()
    }

    // ========================================================================
    // 3. AUTO-GENERATED DOCUMENT IDS
    // ========================================================================

    @Test
    fun testAutoGeneratedDocumentId() = runBlocking {
        val db = KoreDatabase(testDir)
        val logs = db.collection<LogMessage>("logs")

        val id1 = logs.insert(LogMessage("User logged in", "INFO"))
        val id2 = logs.insert(LogMessage("Payment processed", "INFO"))

        assertNotNull(id1)
        assertNotNull(id2)
        assertNotEquals(id1, id2)
        assertTrue(id1.isNotEmpty())
        assertTrue(id2.isNotEmpty())

        val msg1 = logs.getById(id1)
        val msg2 = logs.getById(id2)
        assertNotNull(msg1)
        assertNotNull(msg2)
        assertEquals("User logged in", msg1?.text)
        assertEquals("Payment processed", msg2?.text)

        db.close()
    }

    // ========================================================================
    // 4. TIME-TO-LIVE (TTL / AUTO-EXPIRY)
    // ========================================================================

    @Test
    fun testDocumentTtlExpiration() = runBlocking {
        val db = KoreDatabase(testDir)
        val products = db.collection<Product>("feed_cache")

        // Insert with 1-second TTL
        products.insert("temp_promo", Product("temp_promo", "Flash Sale 50%", "Deals", 49.99), ttlSeconds = 1)
        products.insert("perm_product", Product("perm_product", "Regular Item", "Deals", 99.99), ttlSeconds = 0)

        // Immediately accessible
        val immediate = products.getById("temp_promo")
        assertNotNull(immediate)
        assertEquals("Flash Sale 50%", immediate?.title)

        // Wait for TTL expiration (1.2 seconds)
        kotlinx.coroutines.delay(1200)

        // Expired document must return null on getById
        val expired = products.getById("temp_promo")
        assertNull("Expired document should return null", expired)

        // Permanent product is still accessible
        val perm = products.getById("perm_product")
        assertNotNull("Permanent document should still be present", perm)

        // asSequence() must filter out expired document
        val allValid = products.getAll()
        assertEquals(1, allValid.size)
        assertEquals("perm_product", allValid[0].id)

        db.close()
    }

    // ========================================================================
    // 5. TRANSIENT IN-MEMORY MODE FOR TESTING
    // ========================================================================

    @Test
    fun testInMemoryDatabaseAutoCleansOnClose() = runBlocking {
        val inMemDb = KoreDatabase.inMemory()
        val users = inMemDb.collection<Product>("test_users")

        val id = users.insert(Product("u1", "Test User", "Test", 0.0))
        assertNotNull(users.getById(id))

        // Close the in-memory database
        inMemDb.close()

        // The temporary storage should be completely purged
        // (verified by close callback executing deleteRecursively)
    }
}
